### PR TITLE
fix: Accessibility issue on courseDashboard

### PR DESCRIPTION
**Pull request by omerhabib26**
### Description:

- added content description for views
- make list as default view for MainDashboard

fix: LEARNER-10021

### CODE REVIEW

**Comment by volodymyr-chekyrta** [comment]
Hi @omerhabib26, the Primary Course experience is the default setting for the Open edX application.
We cannot change it.

**Comment by omerhabib26** [comment]
> Hi @omerhabib26, the Primary Course experience is the default setting for the Open edX application. We cannot change it.

As per my understanding the primary course experience API is on sandbox, that's why I changed it to the list. If the change is now available on prod, I can revert it?

**Comment by volodymyr-chekyrta** [comment]
> > Hi @omerhabib26, the Primary Course experience is the default setting for the Open edX application. We cannot change it.
> 
> As per my understanding the primary course experience API is on sandbox, that's why I changed it to the list. If the change is now available on prod, I can revert it?

Changes are not available on prod, so we use the develop branch.
Since the changes will be on prod, we merge this feature into master.

**Review by volodymyr-chekyrta — APPROVED** [review]
@omerhabib26 thank you!
👍

**Review by k1rill — APPROVED** [review]

**Pull request merged**
