### PR TITLE
Feature/in app review

### PR DESCRIPTION
**Pull request by PavloNetrebchuk**
Added in-app review logic:
Show RatingView after the completion of any video.
If the user left negative feedback, choose the "Not Now" option or close the dialog, ask them again after 2 minor or  1 major version.

If the user rated the app from 4 to 5, prompt them to rate it in the Play Store.
Screenshot 2023-10-30 at 17 35 15
Screenshot 2023-10-30 at 17 35 59
Screenshot 2023-10-30 at 17 36 21
Screenshot 2023-10-30 at 17 36 45

If the user rated the app from 1 to 3, prompt them to leave feedback via email.
Screenshot 2023-10-30 at 18 05 41
Screenshot 2023-10-30 at 17 37 41
Screenshot 2023-10-30 at 17 39 51
Screenshot 2023-10-30 at 17 50 40
image
Screenshot 2023-10-30 at 17 43 12

### CODE REVIEW

**Comment by sdaitzman** [comment]
This looks great to me! It would be ideal to collect feedback directly in-app, but that requires some backend communication and is probably not in-scope for now.

**Comment by sdaitzman** [comment]
One question:

- What currently triggers this dialog? Is it timing-based? Could it be triggered only when a video is not actively playing, maybe immediately after a video?

**Comment by volodymyr-chekyrta** [comment]
@sdaitzman 
Yes, the dialog appears when video playback ends

**Review by volodymyr-chekyrta — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@PavloNetrebchuk 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-app-android&entry.867055334=https://github.com/openedx/openedx-app-android/pull/81&entry.1484655318=https://github.com/PavloNetrebchuk&entry.752974735=2023-10-30+16:10&entry.1917517419=2023-11-17+11:51&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
