### PR TITLE
chore: Update dependency versions

### PR DESCRIPTION
**Pull request by volodymyr-chekyrta**
PR includes updates to project dependencies and introduces a workaround for com.microsoft.identity.client:msal for AS Iguana.

Gradle 8.0 -> 8.4
Kotlin 1.8.21 -> 1.9.22
Compose 1.5.0 -> 1.6.2
Compose Compiler 1.4.7 -> 1.5.10
Material 1.9.0 -> 1.11.0
Lifecycle 2.6.1 -> 2.7.0
Fragment 1.6.1 -> 1.6.2
Room 2.5.2 -> 2.6.1
WorkManager 2.8.1 -> 2.9.0
Window 1.1.0 -> 1.2.0
play-services-auth 20.7.0 -> 21.0.0

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @volodymyr-chekyrta! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by nizmaylova** [comment]
Smoke testing passed.

**Review by k1rill — APPROVED** [review]
LGTM!

**Review by farhan-arshad-dev — APPROVED** [review]
The changes LGTM, but this PR introduced some warnings and errors while acting `build -> Rebuild Project`.

**Comment by volodymyr-chekyrta** [comment]
> The changes LGTM, but this PR introduced some warnings and errors while acting `build -> Rebuild Project`.

@farhan-arshad-dev, after investigation, I discovered that executing `build -> Rebuild Project` from the develop branch also triggers an error on my end. 
It appears that this issue is not something newly introduced by the pull request. We may have encountered some new AS Iguana problems.
Can you please double-check or provide more details from the error log?

**Comment by farhan-arshad-dev** [comment]
> > The changes LGTM, but this PR introduced some warnings and errors while acting `build -> Rebuild Project`.
> 
> @farhan-arshad-dev, after investigation, I discovered that executing `build -> Rebuild Project` from the develop branch also triggers an error on my end. It appears that this issue is not something newly introduced by the pull request. We may have encountered some new AS Iguana problems. Can you please double-check or provide more details from the error log?

@volodymyr-chekyrta getting the following logs in Logcat.
issue-1
```
The option setting 'android.defaults.buildfeatures.buildconfig=true' is deprecated.
The current default is 'false'.
It will be removed in version 9.0 of the Android Gradle plugin.
You can resolve this warning in Android Studio via `Refactor` > `Migrate BuildConfig to Gradle Build Files`
```
Issue-2 (produced by multiple modules)
```
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
	at com.android.builder.dexing.D8DexArchiveMerger.getMergingExceptionToRethrow(D8DexArchiveMerger.java:159)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:147)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:884)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:828)
	at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:78)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$0(DefaultWorkerExecutor.java:170)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:187)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.access$700(DefaultConditionalExecutionQueue.java:120)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner$1.run(DefaultConditionalExecutionQueue.java:162)
	at org.gradle.internal.Factories$1.create(Factories.java:31)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:264)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:128)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:133)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:157)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:126)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at Version.fakeStackEntry(Version_8.2.26.java:0)
	at com.android.tools.r8.InternalCompilationFailedExceptionUtils.create(InternalCompilationFailedExceptionUtils.java:29)
	at com.android.tools.r8.utils.ExceptionUtils.failWithFakeEntry(ExceptionUtils.java:144)
	at com.android.tools.r8.utils.ExceptionUtils.failCompilation(ExceptionUtils.java:89)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:83)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:64)
	at com.android.tools.r8.D8.run(D8.java:118)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:145)
	... 38 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at com.android.tools.r8.it.unimi.dsi.fastutil.objects.Reference2IntLinkedOpenHashMap.<init>(Reference2IntLinkedOpenHashMap.java:127)
	at com.android.tools.r8.it.unimi.dsi.fastutil.objects.Reference2IntLinkedOpenHashMap.<init>(Reference2IntLinkedOpenHashMap.java:134)
	at com.android.tools.r8.graph.ObjectToOffsetMapping.createSortedMap(ObjectToOffsetMapping.java:192)
	at com.android.tools.r8.graph.ObjectToOffsetMapping.createSortedMap(ObjectToOffsetMapping.java:178)
	at com.android.tools.r8.graph.ObjectToOffsetMapping.<init>(ObjectToOffsetMapping.java:109)
	at com.android.tools.r8.dex.VirtualFile.computeMapping(VirtualFile.java:230)
	at com.android.tools.r8.dex.VirtualFile.computeMapping(VirtualFile.java:220)
	at com.android.tools.r8.dex.ApplicationWriter.computeOffsetMappingAndRewriteJumboStrings(ApplicationWriter.java:543)
	at com.android.tools.r8.dex.ApplicationWriter.rewriteJumboStringsAndComputeDebugRepresentation(ApplicationWriter.java:304)
	at com.android.tools.r8.dex.ApplicationWriter.lambda$rewriteJumboStringsAndComputeDebugRepresentation$0(ApplicationWriter.java:318)
	at com.android.tools.r8.dex.ApplicationWriter$$Lambda$3157/0x0000000801cef870.apply(Unknown Source)
	at com.android.tools.r8.utils.ThreadUtils.lambda$processItemsWithResults$1(ThreadUtils.java:79)
	at com.android.tools.r8.utils.ThreadUtils$$Lambda$2886/0x0000000801bbba18.apply(Unknown Source)
	at com.android.tools.r8.utils.ThreadUtils.lambda$processItemsWithResults$4(ThreadUtils.java:125)
	at com.android.tools.r8.utils.ThreadUtils$$Lambda$2765/0x0000000801b61490.call(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

```
issue-3 (Related to the  Instrumented tests the test cases in the Android directory can be ignored for now)

Not sure why but not getting warnings logs now but mainly related to the deprecated one like
- Linkify.ALL ('ALL: Int' is deprecated. Deprecated in Java)

**Comment by volodymyr-chekyrta** [comment]
> > > The changes LGTM, but this PR introduced some warnings and errors while acting `build -> Rebuild Project`.
> > 
> > 
> > @farhan-arshad-dev, after investigation, I discovered that executing `build -> Rebuild Project` from the develop branch also triggers an error on my end. It appears that this issue is not something newly introduced by the pull request. We may have encountered some new AS Iguana problems. Can you please double-check or provide more details from the error log?
> 
> @volodymyr-chekyrta getting the following logs in Logcat. issue-1
> 
> ```
> The option setting 'android.defaults.buildfeatures.buildconfig=true' is deprecated.
> The current default is 'false'.
> It will be removed in version 9.0 of the Android Gradle plugin.
> You can resolve this warning in Android Studio via `Refactor` > `Migrate BuildConfig to Gradle Build Files`
> ```
> 
> Issue-2 (produced by multiple modules)
> 
> ```
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
> 	at com.android.builder.dexing.D8DexArchiveMerger.getMergingExceptionToRethrow(D8DexArchiveMerger.java:159)
> 	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:147)
> 	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:884)
> ```
> 
> issue-3 (Related to the Instrumented tests the test cases in the Android directory can be ignored for now)
> 
> Not sure why but not getting warnings logs now but mainly related to the deprecated one like
> 
> * Linkify.ALL ('ALL: Int' is deprecated. Deprecated in Java)

This is even more interesting because I'm getting a completely different error about Gradle DSL 🤣
And are you using the latest version of Android Studio Iguana?

**Comment by farhan-arshad-dev** [comment]
> > > > The changes LGTM, but this PR introduced some warnings and errors while acting `build -> Rebuild Project`.
> > > 
> > > 
> > > @farhan-arshad-dev, after investigation, I discovered that executing `build -> Rebuild Project` from the develop branch also triggers an error on my end. It appears that this issue is not something newly introduced by the pull request. We may have encountered some new AS Iguana problems. Can you please double-check or provide more details from the error log?
> > 
> > 
> > @volodymyr-chekyrta getting the following logs in Logcat. issue-1
> > ```
> > The option setting 'android.defaults.buildfeatures.buildconfig=true' is deprecated.
> > The current default is 'false'.
> > It will be removed in version 9.0 of the Android Gradle plugin.
> > You can resolve this warning in Android Studio via `Refactor` > `Migrate BuildConfig to Gradle Build Files`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Issue-2 (produced by multiple modules)
> > ```
> > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
> > 	at com.android.builder.dexing.D8DexArchiveMerger.getMergingExceptionToRethrow(D8DexArchiveMerger.java:159)
> > 	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:147)
> > 	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:884)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > issue-3 (Related to the Instrumented tests the test cases in the Android directory can be ignored for now)
> > Not sure why but not getting warnings logs now but mainly related to the deprecated one like
> > 
> > * Linkify.ALL ('ALL: Int' is deprecated. Deprecated in Java)
> 
> This is even more interesting because I'm getting a completely different error about Gradle DSL 🤣 And are you using the latest version of Android Studio Iguana?

Yes, the following details
```
Android Studio Iguana | 2023.2.1
Build #AI-232.10227.8.2321.11479570, built on February 22, 2024
Runtime version: 17.0.9+0-17.0.9b1087.7-11185874 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

**Comment by volodymyr-chekyrta** [comment]
> > > > > The changes LGTM, but this PR introduced some warnings and errors while acting `build -> Rebuild Project`.
> > > > 
> > > > 
> > > > @farhan-arshad-dev, after investigation, I discovered that executing `build -> Rebuild Project` from the develop branch also triggers an error on my end. It appears that this issue is not something newly introduced by the pull request. We may have encountered some new AS Iguana problems. Can you please double-check or provide more details from the error log?
> > > 
> > > 
> > > @volodymyr-chekyrta getting the following logs in Logcat. issue-1
> > > ```
> > > The option setting 'android.defaults.buildfeatures.buildconfig=true' is deprecated.
> > > The current default is 'false'.
> > > It will be removed in version 9.0 of the Android Gradle plugin.
> > > You can resolve this warning in Android Studio via `Refactor` > `Migrate BuildConfig to Gradle Build Files`
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Issue-2 (produced by multiple modules)
> > > ```
> > > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
> > > 	at com.android.builder.dexing.D8DexArchiveMerger.getMergingExceptionToRethrow(D8DexArchiveMerger.java:159)
> > > 	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:147)
> > > 	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:884)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > issue-3 (Related to the Instrumented tests the test cases in the Android directory can be ignored for now)
> > > Not sure why but not getting warnings logs now but mainly related to the deprecated one like
> > > 
> > > * Linkify.ALL ('ALL: Int' is deprecated. Deprecated in Java)
> > 
> > 
> > This is even more interesting because I'm getting a completely different error about Gradle DSL 🤣 And are you using the latest version of Android Studio Iguana?
> 
> Yes, the following details
> 
> ```
> Android Studio Iguana | 2023.2.1
> Build #AI-232.10227.8.2321.11479570, built on February 22, 2024
> Runtime version: 17.0.9+0-17.0.9b1087.7-11185874 aarch64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> ```

Could you please check if it removes errors on your side if you revert `'com.android.application'` and `'com.android.library'` to '8.1.1' and the `distributionUrl` to `https\://services.gradle.org/distributions/gradle-8.0-bin.zip`?
Because on my side, I'm getting errors even in the `develop` branch.

Also, I noticed that this error happens on the `Clean project` phase, even without Re/Building.

**Comment by farhan-arshad-dev** [comment]
> Could you please check if it removes errors on your side if you revert 'com.android.application' and 'com.android.library' to '8.1.1' and the distributionUrl to https\://services.gradle.org/distributions/gradle-8.0-bin.zip?
Because on my side, I'm getting errors even in the develop branch.
>
> Also, I noticed that this error happens on the Clean project phase, even without Re/Building.

After these changes still getting the same logs in Logcat. Also observed getting the same logs for other PR, so seems like start producing after the update of Android studio to `Iguana | 2023.2.1`

**Comment by volodymyr-chekyrta** [comment]
> > Could you please check if it removes errors on your side if you revert 'com.android.application' and 'com.android.library' to '8.1.1' and the distributionUrl to https://services.gradle.org/distributions/gradle-8.0-bin.zip?
> > Because on my side, I'm getting errors even in the develop branch.
> > Also, I noticed that this error happens on the Clean project phase, even without Re/Building.
> 
> After these changes still getting the same logs in Logcat. Also observed getting the same logs for other PR, so seems like start producing after the update of Android studio to `Iguana | 2023.2.1`

Same thing 😞 , I think we can merge this PR and then solve the AS Iguana problem in another PR.
Seems to me we need to reorganize the gradle modules a bit, but need time to research.

**Comment by farhan-arshad-dev** [comment]
> hing 😞 , I think we can merge this PR and then solve the AS Iguana problem in another PR.
> Seems to me we need to reorganize the gradle modules a bit, but need time to research.

Sounds good to me.

**Comment by openedx-webhooks** [comment]
@volodymyr-chekyrta 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-app-android&entry.867055334=https://github.com/openedx/openedx-app-android/pull/253&entry.1484655318=https://github.com/volodymyr-chekyrta&entry.752974735=2024-03-05+15:11&entry.1917517419=2024-03-12+07:57&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
