### PR TITLE
Feature/app update

### PR DESCRIPTION
**Pull request by PavloNetrebchuk**
Update required:
 - If a user is not logged in.
Screenshot 2023-10-26 at 16 29 26

 - If a user is logged in.
Screenshot 2023-10-26 at 16 35 18

 - Account settings. The item labeled as "version" can be clicked. Navigation buttons are inactive.
Screenshot 2023-10-26 at 16 36 32

Update recommended:
 - The discovery screen displays a large dialog.
Screenshot 2023-10-27 at 13 26 27

- Users will see small clickable dialog boxes on the discovery and dashboard screens.
Screenshot 2023-10-26 at 16 42 47
Screenshot 2023-10-26 at 16 42 33

 - The button on the profile screen is clickable
Screenshot 2023-10-26 at 16 45 21

Up to date:
Screenshot 2023-10-26 at 16 49 44

Also, it perfectly works with a white theme and landscape.
Screenshot 2023-10-27 at 13 25 39
Screenshot 2023-10-26 at 17 00 43
Screenshot 2023-10-26 at 17 01 27
Screenshot 2023-10-26 at 17 01 39

It will work better with cutouts on a real device. 
Screenshot 2023-10-26 at 16 53 18
And we fixed the navigation bar color in another branch.
Screenshot 2023-10-26 at 16 54 40

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @PavloNetrebchuk!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by sdaitzman** [comment]
Thanks @PavloNetrebchuk! The feature looks good to me.

I did notice some variation in the shades of blue used for accent color and accent text color in dark mode. It might be a compression artifact with the screenshot, can you confirm if they match the correct values in the build?

image

**Comment by PavloNetrebchuk** [comment]
Hello @sdaitzman 
I agree with you. I have already made the necessary changes.
Screenshot 2023-10-27 at 19 32 38

**Comment by sdaitzman** [comment]
Thank you! That looks right to me

**Comment by openedx-webhooks** [comment]
@PavloNetrebchuk 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-app-android&entry.867055334=https://github.com/openedx/openedx-app-android/pull/79&entry.1484655318=https://github.com/PavloNetrebchuk&entry.752974735=2023-10-26+14:03&entry.1917517419=2023-11-02+14:15&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
