### PR TITLE
Feature/landscape

### PR DESCRIPTION
**Pull request by PavloNetrebchuk**
Landscape support for full application

Screenshot 2023-10-12 at 19 47 25

Screenshot 2023-10-12 at 19 50 34

Screenshot 2023-10-12 at 19 49 53

Screenshot 2023-10-12 at 19 52 07

Screenshot 2023-10-12 at 19 52 51

### CODE REVIEW

**Comment by sdaitzman** [comment]
This looks great! Here are some mocks with slight proposed design changes to the landscape "Good work!" dialog and video-with-transcript views. I'll update soon with similar proposed changes for portrait mode "Good work!" dialogs and web-view blocks

image
The landscape video-with-transcript view repositions the back button, title, and next/previous buttons in a unified bar at the top, and uses the extra space to expand the video and transcript


image

The “Good work!” dialog has an added dismiss button to allow users to continue viewing the section before moving on

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @PavloNetrebchuk!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by adding a comment here that you have signed it.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by mphilbrick211** [comment]
Hi @PavloNetrebchuk! If you are contributing on behalf of Raccoon Gang, please have your manager email [oscm@axim.org](oscm@axim.org) in order to add you to the existing Raccoon Gang entity CLA form. Thank you!

**Comment by PavloNetrebchuk** [comment]
Hello @marcotuts @sdaitzman !
I added changes and added new screenshots in the description

**Comment by sdaitzman** [comment]
Thanks for the update, I think this looks good and addresses the suggested changes we identified!





In this screenshot, if the phone is rotated 180˚ so the camera is on the right, will it overlap with the progress dots on the right, or are they positioned to adjust within the safe area?

**Comment by PavloNetrebchuk** [comment]
@sdaitzman 
Yes, it overlap with the progress dots
IMG_20231012_214347

**Comment by PavloNetrebchuk** [comment]
@sdaitzman We have resolved the issue 👍
IMG_20231013_162229

**Review by marcotuts — APPROVED** [review]
Product review complete - thanks!

**Review by volodymyr-chekyrta — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@PavloNetrebchuk 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-app-android&entry.867055334=https://github.com/openedx/openedx-app-android/pull/68&entry.1484655318=https://github.com/PavloNetrebchuk&entry.752974735=2023-10-05+12:44&entry.1917517419=2023-10-16+13:34&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
