### PR TITLE
Discussion's user profile

### PR DESCRIPTION
**Pull request by PavloNetrebchuk**
Added screen of another user profile, with an option to open it from the discussion screen. 
Full name and year of birth are displayed only for staff members.

Below are scenarios of what a profile might look like:
- Learner viewing user profile without bio
Screenshot 2023-10-09 at 19 31 36
- Learner viewing user profile with bio
Screenshot 2023-10-09 at 19 31 59
- Staff user viewing user profile with bio
Screenshot 2023-10-09 at 19 32 53

### CODE REVIEW

**Comment by marcotuts** [comment]
Would you mind adding some descriptors between each for the images for the sake of clarity? My guess at the headings below for example: 

- Learner viewing User without bio
- Learner viewing User with bio
- Staff user viewing User with bio

**Comment by volodymyr-chekyrta** [comment]
Thanks @marcotuts 🙌
Description is updated.

**Comment by marcotuts** [comment]
No other product / design feedback thanks!

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @PavloNetrebchuk!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by volodymyr-chekyrta — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@PavloNetrebchuk 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-app-android&entry.867055334=https://github.com/openedx/openedx-app-android/pull/69&entry.1484655318=https://github.com/PavloNetrebchuk&entry.752974735=2023-10-09+16:37&entry.1917517419=2023-10-13+09:53&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
