### PR TITLE
chore: Remove in-code ukranian translations | FC-55

### PR DESCRIPTION
**Pull request by OmarIthawi**
Clean up after #317 is merged.

`make pull_translations` should be used before release

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by OmarIthawi** [comment]
@k1rill would you mind triaging this PR?

**Comment by OmarIthawi** [comment]
@brian-smith-tcril @volodymyr-chekyrta @k1rill this is ready for review.

Please let me know if you have any questions or notes.

**Comment by OmarIthawi** [comment]
@k1rill would you mind checking this pull request? This is the only remaining part of the FC-55 for the android project.

cc: @marcotuts

**Review by volodymyr-chekyrta — APPROVED** [review]
LGMT 👍

**Comment by openedx-webhooks** [comment]
@OmarIthawi 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-app-android&entry.867055334=https://github.com/openedx/openedx-app-android/pull/342&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2024-06-13+21:04&entry.1917517419=2024-08-19+07:28&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
