### PR TITLE
Fix: Android Studio Iguana build issues

### PR DESCRIPTION
**Pull request by volodymyr-chekyrta**
This pull request addresses issues that arose following the release of Android Studio Iguana.

`Build -> Clean Project` problem:
Screenshot 2024-03-20 at 13 50 00

`Build -> Rebuild Project` problem:
Screenshot 2024-03-20 at 13 49 10

Note: Jetpack Compose tests have been removed due to prolonged lack of maintenance, resulting in compile errors during the build process.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @volodymyr-chekyrta! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by k1rill — APPROVED** [review]
LGTM!

**Review by farhan-arshad-dev — COMMENTED** [review]
I'm still getting logs
- `java.lang.OutOfMemoryError: Java heap space`
- `com.android.tools.r8.CompilationFailedException: Compilation failed to complete`
- `java.lang.OutOfMemoryError: Java heap space`

Screenshot 2024-03-22 at 3 47 25 PM

**Comment by farhan-arshad-dev** [comment]
@volodymyr-chekyrta After updating the `org.gradle.jvmargs` `-Xmx2048m -Dfile.encoding=UTF-8` -> `-Xmx4608m -Dfile.encoding=UTF-8` in [gradle.properties](https://github.com/openedx/openedx-app-android/blob/main/gradle.properties#L9) error got fixed, but warnings are still there.

Screenshot 2024-03-22 at 3 55 12 PM

IMO, it's better to consider the warning to be fixed as part of this PR.

**Comment by volodymyr-chekyrta** [comment]
> @volodymyr-chekyrta After updating the `org.gradle.jvmargs` `-Xmx2048m -Dfile.encoding=UTF-8` -> `-Xmx4608m -Dfile.encoding=UTF-8` in [gradle.properties](https://github.com/openedx/openedx-app-android/blob/main/gradle.properties#L9) error got fixed, but warnings are still there.
> 
> Screenshot 2024-03-22 at 3 55 12 PM
> IMO, it's better to consider the warning to be fixed as part of this PR.

@farhan-arshad-dev 
Yes, I left this issue for future investigation. On my machine that value should be at least `-Xmx6144m`, so it looks like we'll have to wait for Android Studio to sort it out.

**Comment by volodymyr-chekyrta** [comment]
> IMO, it's better to consider the warning to be fixed as part of this PR.

@farhan-arshad-dev, this PR concentrates on fixing critical build issues, lets fix warnings in the separate code health PR

**Review by farhan-arshad-dev — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@volodymyr-chekyrta 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-app-android&entry.867055334=https://github.com/openedx/openedx-app-android/pull/265&entry.1484655318=https://github.com/volodymyr-chekyrta&entry.752974735=2024-03-20+12:01&entry.1917517419=2024-03-22+11:30&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
