### PR TITLE
fix: changed the button name when trying to create a question

### PR DESCRIPTION
**Pull request by dixidroid**
Changed the name of the button to "Create question" when trying to create a question in a discussion

### CODE REVIEW

**Review by volodymyr-chekyrta — APPROVED** [review]

**Review by k1rill — DISMISSED** [review]

**Review by HamzaIsrar12 — DISMISSED** [review]

**Comment by HamzaIsrar12** [comment]
@dixidroid Do we have a separate issue for updating the screen title? 🤔

**Comment by dixidroid** [comment]
@HamzaIsrar12 fixed the screen title too

**Review by HamzaIsrar12 — APPROVED** [review]
LGTM 🏎️

**Review by volodymyr-chekyrta — APPROVED** [review]

**Comment by volodymyr-chekyrta** [comment]
@dixidroid, could you please resolve the conflict?

**Review by volodymyr-chekyrta — APPROVED** [review]

**Pull request merged**
