### PR TITLE
What's new

### PR DESCRIPTION
**Pull request by PavloNetrebchuk**
Added what's new screen
Screenshot 2023-10-25 at 15 04 49
Screenshot 2023-10-25 at 14 58 42
Screenshot 2023-10-25 at 14 58 58
Screenshot 2023-10-25 at 14 59 09

Video:
https://github.com/openedx/openedx-app-android/assets/141041606/37399f05-7e0b-4762-8e44-d3dee4e8fabf

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @PavloNetrebchuk!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by marcotuts** [comment]
Minor note / question from me - is the backgroudn color of the bottom bar something that can be changed? I noticed that for bot hlight and dark modes the color differs from the background screen. If it is possible to match the same color that would be great.

image

image

**Comment by volodymyr-chekyrta** [comment]
> Minor note / question from me - is the backgroudn color of the bottom bar something that can be changed? I noticed that for bot hlight and dark modes the color differs from the background screen. If it is possible to match the same color that would be great.
> 
> image image

@marcotuts
It looks like we can implement that behavior, but it might affect all screens in the application. Is that alright?  
More info: https://developer.android.com/develop/ui/views/layout/edge-to-edge.

**Comment by sdaitzman** [comment]
Thank you, these screens look really great!! I only see a few very small potential changes (these are really specific, I don't think they need to be changed to move forward):

- When the title is close to the top cutout (camera punch in this case) in portrait mode, is it possible to shift the title down by 8px so the text isn't right up next to the cutout? This would also apply to the other titlebars, like in the Discover tab.
- In the Figma designs, update text is vertically snapped to the bottom above the buttons, rather than the top underneath the title. I think it looks good either way here, so I just updated the Figma designs to match this.
- As the "Previous" button appears, its icon spins around a bit. Can the animation only be an opacity fade in, without the icon moving?

I don't think these are important enough to spend a lot of time updating, everything looks good to me! Cross-posting a similar comment here https://github.com/openedx/openedx-app-ios/pull/131

**Comment by marcotuts** [comment]
I think having this be transparent would be great for all screens, if this causes issues elsewhere we can reverse course but that seems like it'll work

**Comment by PavloNetrebchuk** [comment]
> Thank you, these screens look really great!! I only see a few very small potential changes (these are really specific, I don't think they need to be changed to move forward):
> 
> * When the title is close to the top cutout (camera punch in this case) in portrait mode, is it possible to shift the title down by 8px so the text isn't right up next to the cutout? This would also apply to the other titlebars, like in the Discover tab.
> * In the Figma designs, update text is vertically snapped to the bottom above the buttons, rather than the top underneath the title. I think it looks good either way here, so I just updated the Figma designs to match this.
> * As the "Previous" button appears, its icon spins around a bit. Can the animation only be an opacity fade in, without the icon moving?
> 
> I don't think these are important enough to spend a lot of time updating, everything looks good to me! Cross-posting a similar comment here [openedx/openedx-app-ios#131](https://github.com/openedx/openedx-app-ios/pull/131)

Hello, @sdaitzman 
1. The emulator does not work well with the cutout, but we don't have that problem on real devices.
2. Thank you.
3. I have resolved the issue.

https://github.com/openedx/openedx-app-android/assets/141041606/6532711c-2348-4887-acb7-893fd773ff45

**Comment by PavloNetrebchuk** [comment]
> I think having this be transparent would be great for all screens, if this causes issues elsewhere we can reverse course but that seems like it'll work

Done it. On most screens, the behavior will be the same.
Screenshot 2023-10-26 at 12 10 37
Screenshot 2023-10-26 at 12 10 54
Screenshot 2023-10-26 at 12 11 07
Screenshot 2023-10-26 at 12 11 27
Screenshot 2023-10-26 at 12 14 14
Screenshot 2023-10-26 at 12 14 30

**Comment by sdaitzman** [comment]
Thanks @PavloNetrebchuk, this all looks great to me!

**Review by volodymyr-chekyrta — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@PavloNetrebchuk 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-app-android&entry.867055334=https://github.com/openedx/openedx-app-android/pull/77&entry.1484655318=https://github.com/PavloNetrebchuk&entry.752974735=2023-10-23+12:54&entry.1917517419=2023-10-27+09:02&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
